// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.26.0
// source: api/monthCard/v1/monthCard_errorCode.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCode int32

const (
	ErrorCode_NET_WORK_ERROR                        ErrorCode = 0
	ErrorCode_USER_NOT_FOUND                        ErrorCode = 1
	ErrorCode_MONTH_CARD_HAVE_OPENED_ERROR          ErrorCode = 2
	ErrorCode_MONTH_CARD_NOT_OPEN                   ErrorCode = 3
	ErrorCode_MONTH_CARD_REWARD_HAVE_RECEIVED_ERROR ErrorCode = 4
	ErrorCode_MONTH_CARD_REWARD_FAILED_ERROR        ErrorCode = 5
)

// Enum value maps for ErrorCode.
var (
	ErrorCode_name = map[int32]string{
		0: "NET_WORK_ERROR",
		1: "USER_NOT_FOUND",
		2: "MONTH_CARD_HAVE_OPENED_ERROR",
		3: "MONTH_CARD_NOT_OPEN",
		4: "MONTH_CARD_REWARD_HAVE_RECEIVED_ERROR",
		5: "MONTH_CARD_REWARD_FAILED_ERROR",
	}
	ErrorCode_value = map[string]int32{
		"NET_WORK_ERROR":                        0,
		"USER_NOT_FOUND":                        1,
		"MONTH_CARD_HAVE_OPENED_ERROR":          2,
		"MONTH_CARD_NOT_OPEN":                   3,
		"MONTH_CARD_REWARD_HAVE_RECEIVED_ERROR": 4,
		"MONTH_CARD_REWARD_FAILED_ERROR":        5,
	}
)

func (x ErrorCode) Enum() *ErrorCode {
	p := new(ErrorCode)
	*p = x
	return p
}

func (x ErrorCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCode) Descriptor() protoreflect.EnumDescriptor {
	return file_api_monthCard_v1_monthCard_errorCode_proto_enumTypes[0].Descriptor()
}

func (ErrorCode) Type() protoreflect.EnumType {
	return &file_api_monthCard_v1_monthCard_errorCode_proto_enumTypes[0]
}

func (x ErrorCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCode.Descriptor instead.
func (ErrorCode) EnumDescriptor() ([]byte, []int) {
	return file_api_monthCard_v1_monthCard_errorCode_proto_rawDescGZIP(), []int{0}
}

var File_api_monthCard_v1_monthCard_errorCode_proto protoreflect.FileDescriptor

var file_api_monthCard_v1_monthCard_errorCode_proto_rawDesc = []byte{
	0x0a, 0x2a, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x43, 0x61, 0x72, 0x64, 0x2f,
	0x76, 0x31, 0x2f, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x43, 0x61, 0x72, 0x64, 0x5f, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x61, 0x70,
	0x69, 0x2e, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x43, 0x61, 0x72, 0x64, 0x2e, 0x76, 0x31, 0x2a, 0xbd,
	0x01, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x0e,
	0x4e, 0x45, 0x54, 0x5f, 0x57, 0x4f, 0x52, 0x4b, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x00,
	0x12, 0x12, 0x0a, 0x0e, 0x55, 0x53, 0x45, 0x52, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x46, 0x4f, 0x55,
	0x4e, 0x44, 0x10, 0x01, 0x12, 0x20, 0x0a, 0x1c, 0x4d, 0x4f, 0x4e, 0x54, 0x48, 0x5f, 0x43, 0x41,
	0x52, 0x44, 0x5f, 0x48, 0x41, 0x56, 0x45, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x45, 0x44, 0x5f, 0x45,
	0x52, 0x52, 0x4f, 0x52, 0x10, 0x02, 0x12, 0x17, 0x0a, 0x13, 0x4d, 0x4f, 0x4e, 0x54, 0x48, 0x5f,
	0x43, 0x41, 0x52, 0x44, 0x5f, 0x4e, 0x4f, 0x54, 0x5f, 0x4f, 0x50, 0x45, 0x4e, 0x10, 0x03, 0x12,
	0x29, 0x0a, 0x25, 0x4d, 0x4f, 0x4e, 0x54, 0x48, 0x5f, 0x43, 0x41, 0x52, 0x44, 0x5f, 0x52, 0x45,
	0x57, 0x41, 0x52, 0x44, 0x5f, 0x48, 0x41, 0x56, 0x45, 0x5f, 0x52, 0x45, 0x43, 0x45, 0x49, 0x56,
	0x45, 0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x04, 0x12, 0x22, 0x0a, 0x1e, 0x4d, 0x4f,
	0x4e, 0x54, 0x48, 0x5f, 0x43, 0x41, 0x52, 0x44, 0x5f, 0x52, 0x45, 0x57, 0x41, 0x52, 0x44, 0x5f,
	0x46, 0x41, 0x49, 0x4c, 0x45, 0x44, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x10, 0x05, 0x42, 0x33,
	0x0a, 0x10, 0x61, 0x70, 0x69, 0x2e, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x43, 0x61, 0x72, 0x64, 0x2e,
	0x76, 0x31, 0x50, 0x01, 0x5a, 0x1d, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x43, 0x61, 0x72, 0x64, 0x2f,
	0x61, 0x70, 0x69, 0x2f, 0x6d, 0x6f, 0x6e, 0x74, 0x68, 0x43, 0x61, 0x72, 0x64, 0x2f, 0x76, 0x31,
	0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_monthCard_v1_monthCard_errorCode_proto_rawDescOnce sync.Once
	file_api_monthCard_v1_monthCard_errorCode_proto_rawDescData = file_api_monthCard_v1_monthCard_errorCode_proto_rawDesc
)

func file_api_monthCard_v1_monthCard_errorCode_proto_rawDescGZIP() []byte {
	file_api_monthCard_v1_monthCard_errorCode_proto_rawDescOnce.Do(func() {
		file_api_monthCard_v1_monthCard_errorCode_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_monthCard_v1_monthCard_errorCode_proto_rawDescData)
	})
	return file_api_monthCard_v1_monthCard_errorCode_proto_rawDescData
}

var file_api_monthCard_v1_monthCard_errorCode_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_monthCard_v1_monthCard_errorCode_proto_goTypes = []any{
	(ErrorCode)(0), // 0: api.monthCard.v1.ErrorCode
}
var file_api_monthCard_v1_monthCard_errorCode_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_monthCard_v1_monthCard_errorCode_proto_init() }
func file_api_monthCard_v1_monthCard_errorCode_proto_init() {
	if File_api_monthCard_v1_monthCard_errorCode_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_monthCard_v1_monthCard_errorCode_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_monthCard_v1_monthCard_errorCode_proto_goTypes,
		DependencyIndexes: file_api_monthCard_v1_monthCard_errorCode_proto_depIdxs,
		EnumInfos:         file_api_monthCard_v1_monthCard_errorCode_proto_enumTypes,
	}.Build()
	File_api_monthCard_v1_monthCard_errorCode_proto = out.File
	file_api_monthCard_v1_monthCard_errorCode_proto_rawDesc = nil
	file_api_monthCard_v1_monthCard_errorCode_proto_goTypes = nil
	file_api_monthCard_v1_monthCard_errorCode_proto_depIdxs = nil
}
