// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"monthCard/internal/biz"
	"monthCard/internal/conf"
	"monthCard/internal/data"
	"monthCard/internal/server"
	"monthCard/internal/service"
)

import (
	_ "go.uber.org/automaxprocs"
)

// Injectors from wire.go:

// wireApp init kratos application.
func wireApp(confServer *conf.Server, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db, err := data.NewGormDB(confData)
	if err != nil {
		return nil, nil, err
	}
	client, err := data.NewRedisClient(confData)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(db, client, logger)
	if err != nil {
		return nil, nil, err
	}
	monthCardRepo := data.NewMonthCardRepo(dataData, logger)
	monthCardUsecase := biz.NewMonthCardUsecase(monthCardRepo, logger)
	monthCardService := service.NewMonthCardService(monthCardUsecase, logger)
	grpcServer := server.NewGRPCServer(confServer, monthCardService, logger)
	httpServer := server.NewHTTPServer(confServer, monthCardService, logger)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
		cleanup()
	}, nil
}
